version: 2
updates:
  - package-ecosystem: npm
    directory: /web
    schedule: { interval: weekly }
  - package-ecosystem: nuget
    directory: /csharp/Architecture.Api
    schedule: { interval: weekly }
  - package-ecosystem: maven
    directory: /java
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /csharp
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /java
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /web
    schedule: { interval: weekly }
